// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// App Engine target. The job will be pushed to a job handler by means
/// of an HTTP request via an
/// [http_method][google.cloud.scheduler.v1.AppEngineHttpTarget.http_method] such
/// as HTTP POST, HTTP GET, etc. The job is acknowledged by means of an
/// HTTP response code in the range [200 - 299]. Error 503 is
/// considered an App Engine system error instead of an application
/// error. Requests returning error 503 will be retried regardless of
/// retry configuration and not counted against retry counts. Any other
/// response code, or a failure to receive a response before the
/// deadline, constitutes a failed attempt.
///
/// [google.cloud.scheduler.v1.AppEngineHttpTarget.http_method]: <doc:AppEngineHttpTarget/httpMethod>
public struct AppEngineHttpTarget: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The HTTP method to use for the request. PATCH and OPTIONS are not
  /// permitted.
  public var httpMethod: HttpMethod = HttpMethod()

  /// App Engine Routing setting for the job.
  public var appEngineRouting: AppEngineRouting? = nil

  /// The relative URI.
  ///
  /// The relative URL must begin with "/" and must be a valid HTTP relative URL.
  /// It can contain a path, query string arguments, and `#` fragments.
  /// If the relative URL is empty, then the root path "/" will be used.
  /// No spaces are allowed, and the maximum length allowed is 2083 characters.
  public var relativeUri: Swift.String = Swift.String()

  /// HTTP request headers.
  ///
  /// This map contains the header field names and values. Headers can be set
  /// when the job is created.
  ///
  /// Cloud Scheduler sets some headers to default values:
  ///
  /// * `User-Agent`: By default, this header is
  ///   `"AppEngine-Google; (+http://code.google.com/appengine)"`.
  ///   This header can be modified, but Cloud Scheduler will append
  ///   `"AppEngine-Google; (+http://code.google.com/appengine)"` to the
  ///   modified `User-Agent`.
  /// * `X-CloudScheduler`: This header will be set to true.
  /// * `X-CloudScheduler-JobName`: This header will contain the job name.
  /// * `X-CloudScheduler-ScheduleTime`: For Cloud Scheduler jobs specified in
  /// the unix-cron format, this header will contain the job schedule as an
  /// offset of UTC parsed according to RFC3339.
  ///
  /// If the job has a [body][google.cloud.scheduler.v1.AppEngineHttpTarget.body]
  /// and the following headers are not set by the user, Cloud Scheduler sets
  /// default values:
  ///
  /// * `Content-Type`: This will be set to `"application/octet-stream"`. You
  ///   can override this default by explicitly setting `Content-Type` to a
  ///   particular media type when creating the job. For example, you can set
  ///   `Content-Type` to `"application/json"`.
  ///
  /// The headers below are output only. They cannot be set or overridden:
  ///
  /// * `Content-Length`: This is computed by Cloud Scheduler.
  /// * `X-Google-*`: For Google internal use only.
  /// * `X-AppEngine-*`: For Google internal use only.
  ///
  /// In addition, some App Engine headers, which contain
  /// job-specific information, are also be sent to the job handler.
  ///
  /// [google.cloud.scheduler.v1.AppEngineHttpTarget.body]: <doc:AppEngineHttpTarget/body>
  public var headers: [Swift.String: Swift.String] = [:]

  /// Body.
  ///
  /// HTTP request body. A request body is allowed only if the HTTP method is
  /// POST or PUT. It will result in invalid argument error to set a body on a
  /// job with an incompatible
  /// [HttpMethod][google.cloud.scheduler.v1.HttpMethod].
  ///
  /// [google.cloud.scheduler.v1.HttpMethod]: <doc:HttpMethod>
  public var body: Foundation.Data = Foundation.Data()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AppEngineHttpTarget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppEngineHttpTarget().with { $0.httpMethod = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let httpMethod = CodingKeys(stringValue: "httpMethod")
    static let appEngineRouting = CodingKeys(stringValue: "appEngineRouting")
    static let relativeUri = CodingKeys(stringValue: "relativeUri")
    static let headers = CodingKeys(stringValue: "headers")
    static let body = CodingKeys(stringValue: "body")

    static let _knownKeys: Set<Swift.String> = [
      "httpMethod",
      "appEngineRouting",
      "relativeUri",
      "headers",
      "body",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(HttpMethod.self, forKey: .httpMethod) {
      self.httpMethod = value
    }
    self.appEngineRouting = try container.decodeIfPresent(
      AppEngineRouting.self, forKey: .appEngineRouting)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .relativeUri) {
      self.relativeUri = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .headers)
    {
      self.headers = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .body) {
      self.body = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.httpMethod, forKey: .httpMethod)
    try container.encodeIfPresent(self.appEngineRouting, forKey: .appEngineRouting)
    try container.encode(self.relativeUri, forKey: .relativeUri)
    try container.encode(self.headers, forKey: .headers)
    try container.encode(self.body, forKey: .body)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.scheduler.v1.AppEngineHttpTarget"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
