// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The Cloud Scheduler API allows external entities to reliably
/// schedule asynchronous jobs.
///
/// @Snippet(path: "CloudSchedulerQuickstart")
public final class CloudSchedulerClient: Clients.CloudSchedulerProtocol, Sendable {
  let inner: any Clients.CloudSchedulerStub

  /// Creates a new `CloudSchedulerClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudSchedulerStub = try Clients.CloudSchedulerTransport(options)
    inner = Clients.CloudSchedulerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudSchedulerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists jobs.
  ///
  /// @Snippet(path: "CloudScheduler_ListJobs")
  public func listJobs(
    request: ListJobsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.ListJobsResponse {
    try await self.inner.listJobs(request: request, options: options)
  }

  /// Gets a job.
  ///
  /// @Snippet(path: "CloudScheduler_GetJob")
  public func getJob(
    request: GetJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.inner.getJob(request: request, options: options)
  }

  /// Creates a job.
  ///
  /// @Snippet(path: "CloudScheduler_CreateJob")
  public func createJob(
    request: CreateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.inner.createJob(request: request, options: options)
  }

  /// Updates a job.
  ///
  /// If successful, the updated [Job][google.cloud.scheduler.v1.Job] is
  /// returned. If the job does not exist, `NOT_FOUND` is returned.
  ///
  /// If UpdateJob does not successfully return, it is possible for the
  /// job to be in an
  /// [Job.State.UPDATE_FAILED][google.cloud.scheduler.v1.Job.State.UPDATE_FAILED]
  /// state. A job in this state may not be executed. If this happens, retry the
  /// UpdateJob request until a successful response is received.
  ///
  /// [google.cloud.scheduler.v1.Job]: <doc:Job>
  /// [google.cloud.scheduler.v1.Job.State.UPDATE_FAILED]: <doc:Job/State/updateFailed>
  ///
  /// @Snippet(path: "CloudScheduler_UpdateJob")
  public func updateJob(
    request: UpdateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.inner.updateJob(request: request, options: options)
  }

  /// Deletes a job.
  ///
  /// @Snippet(path: "CloudScheduler_DeleteJob")
  public func deleteJob(
    request: DeleteJobRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteJob(request: request, options: options)
  }

  /// Pauses a job.
  ///
  /// If a job is paused then the system will stop executing the job
  /// until it is re-enabled via
  /// [ResumeJob][google.cloud.scheduler.v1.CloudScheduler.ResumeJob]. The state
  /// of the job is stored in [state][google.cloud.scheduler.v1.Job.state]; if
  /// paused it will be set to
  /// [Job.State.PAUSED][google.cloud.scheduler.v1.Job.State.PAUSED]. A job must
  /// be in [Job.State.ENABLED][google.cloud.scheduler.v1.Job.State.ENABLED] to
  /// be paused.
  ///
  /// [google.cloud.scheduler.v1.CloudScheduler.ResumeJob]: <doc:CloudSchedulerClient/resumeJob(request:options:)>
  /// [google.cloud.scheduler.v1.Job.State.ENABLED]: <doc:Job/State/enabled>
  /// [google.cloud.scheduler.v1.Job.State.PAUSED]: <doc:Job/State/paused>
  /// [google.cloud.scheduler.v1.Job.state]: <doc:Job/state>
  ///
  /// @Snippet(path: "CloudScheduler_PauseJob")
  public func pauseJob(
    request: PauseJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.inner.pauseJob(request: request, options: options)
  }

  /// Resume a job.
  ///
  /// This method reenables a job after it has been
  /// [Job.State.PAUSED][google.cloud.scheduler.v1.Job.State.PAUSED]. The state
  /// of a job is stored in [Job.state][google.cloud.scheduler.v1.Job.state];
  /// after calling this method it will be set to
  /// [Job.State.ENABLED][google.cloud.scheduler.v1.Job.State.ENABLED]. A job
  /// must be in [Job.State.PAUSED][google.cloud.scheduler.v1.Job.State.PAUSED]
  /// to be resumed.
  ///
  /// [google.cloud.scheduler.v1.Job.State.ENABLED]: <doc:Job/State/enabled>
  /// [google.cloud.scheduler.v1.Job.State.PAUSED]: <doc:Job/State/paused>
  /// [google.cloud.scheduler.v1.Job.state]: <doc:Job/state>
  ///
  /// @Snippet(path: "CloudScheduler_ResumeJob")
  public func resumeJob(
    request: ResumeJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.inner.resumeJob(request: request, options: options)
  }

  /// Forces a job to run now.
  ///
  /// When this method is called, Cloud Scheduler will dispatch the job, even
  /// if the job is already running.
  ///
  /// @Snippet(path: "CloudScheduler_RunJob")
  public func runJob(
    request: RunJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.inner.runJob(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudScheduler_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CloudScheduler_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudSchedulerClient`.
  ///
  /// To mock `CloudSchedulerClient` change your functions to receive
  /// `some CloudSchedulerProtocol` or `any CloudSchedulerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudSchedulerProtocol: Sendable {
    /// See `CloudSchedulerClient.listJobs`.
    func listJobs(
      request: ListJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.ListJobsResponse

    /// See `CloudSchedulerClient.getJob`.
    func getJob(
      request: GetJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    /// See `CloudSchedulerClient.createJob`.
    func createJob(
      request: CreateJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    /// See `CloudSchedulerClient.updateJob`.
    func updateJob(
      request: UpdateJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    /// See `CloudSchedulerClient.deleteJob`.
    func deleteJob(
      request: DeleteJobRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `CloudSchedulerClient.pauseJob`.
    func pauseJob(
      request: PauseJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    /// See `CloudSchedulerClient.resumeJob`.
    func resumeJob(
      request: ResumeJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    /// See `CloudSchedulerClient.runJob`.
    func runJob(
      request: RunJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    /// See `CloudSchedulerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudSchedulerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.CloudSchedulerProtocol {
  public func listJobs(request: ListJobsRequest) async throws
    -> GoogleCloudSchedulerV1.ListJobsResponse
  {
    try await self.listJobs(request: request, options: .init())
  }

  public func listJobs(
    request: ListJobsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.ListJobsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listJobs(
    byItem: ListJobsRequest
  ) -> any AsyncSequence<Job, Swift.Error> {
    self.listJobs(byItem: byItem, options: .init())
  }

  /// Lists jobs.
  ///
  /// @Snippet(path: "CloudScheduler_ListJobs")
  public func listJobs(
    byItem: ListJobsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Job, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudSchedulerV1.ListJobsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listJobs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listJobs(
    parent: Swift.String,
  ) -> any AsyncSequence<Job, Swift.Error> {
    let request = ListJobsRequest().with {
      $0.parent = parent
    }
    return self.listJobs(byItem: request)
  }

  public func getJob(request: GetJobRequest) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.getJob(request: request, options: .init())
  }

  public func getJob(
    request: GetJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getJob(
    name: Swift.String,
  ) async throws -> GoogleCloudSchedulerV1.Job {
    let request = GetJobRequest().with {
      $0.name = name
    }
    return try await self.getJob(request: request)
  }

  public func createJob(request: CreateJobRequest) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.createJob(request: request, options: .init())
  }

  public func createJob(
    request: CreateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createJob(
    parent: Swift.String,
    job: Job?,
  ) async throws -> GoogleCloudSchedulerV1.Job {
    let request = CreateJobRequest().with {
      $0.parent = parent
      $0.job = job
    }
    return try await self.createJob(request: request)
  }

  public func updateJob(request: UpdateJobRequest) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.updateJob(request: request, options: .init())
  }

  public func updateJob(
    request: UpdateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateJob(
    job: Job?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudSchedulerV1.Job {
    let request = UpdateJobRequest().with {
      $0.job = job
      $0.updateMask = updateMask
    }
    return try await self.updateJob(request: request)
  }

  public func deleteJob(request: DeleteJobRequest) async throws {
    try await self.deleteJob(request: request, options: .init())
  }

  public func deleteJob(
    request: DeleteJobRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteJob(
    name: Swift.String,
  ) async throws {
    let request = DeleteJobRequest().with {
      $0.name = name
    }
    try await self.deleteJob(request: request)
  }

  public func pauseJob(request: PauseJobRequest) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.pauseJob(request: request, options: .init())
  }

  public func pauseJob(
    request: PauseJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    throw GoogleGax.RequestError.unimplemented
  }

  public func pauseJob(
    name: Swift.String,
  ) async throws -> GoogleCloudSchedulerV1.Job {
    let request = PauseJobRequest().with {
      $0.name = name
    }
    return try await self.pauseJob(request: request)
  }

  public func resumeJob(request: ResumeJobRequest) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.resumeJob(request: request, options: .init())
  }

  public func resumeJob(
    request: ResumeJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    throw GoogleGax.RequestError.unimplemented
  }

  public func resumeJob(
    name: Swift.String,
  ) async throws -> GoogleCloudSchedulerV1.Job {
    let request = ResumeJobRequest().with {
      $0.name = name
    }
    return try await self.resumeJob(request: request)
  }

  public func runJob(request: RunJobRequest) async throws -> GoogleCloudSchedulerV1.Job {
    try await self.runJob(request: request, options: .init())
  }

  public func runJob(
    request: RunJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSchedulerV1.Job {
    throw GoogleGax.RequestError.unimplemented
  }

  public func runJob(
    name: Swift.String,
  ) async throws -> GoogleCloudSchedulerV1.Job {
    let request = RunJobRequest().with {
      $0.name = name
    }
    return try await self.runJob(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocations(byItem: byItem, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudScheduler_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }
}
