// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The HTTP method used to execute the job.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum HttpMethod: Codable, Equatable, Hashable, Sendable {
  /// HTTP method unspecified. Defaults to POST.
  case unspecified
  /// HTTP POST
  case post
  /// HTTP GET
  case `get`
  /// HTTP HEAD
  case head
  /// HTTP PUT
  case put
  /// HTTP DELETE
  case delete
  /// HTTP PATCH
  case patch
  /// HTTP OPTIONS
  case options
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .post: return 1
    case .`get`: return 2
    case .head: return 3
    case .put: return 4
    case .delete: return 5
    case .patch: return 6
    case .options: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "HTTP_METHOD_UNSPECIFIED"
    case .post: return "POST"
    case .`get`: return "GET"
    case .head: return "HEAD"
    case .put: return "PUT"
    case .delete: return "DELETE"
    case .patch: return "PATCH"
    case .options: return "OPTIONS"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HttpMethod/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "HTTP_METHOD_UNSPECIFIED": self = .unspecified
    case "POST": self = .post
    case "GET": self = .`get`
    case "HEAD": self = .head
    case "PUT": self = .put
    case "DELETE": self = .delete
    case "PATCH": self = .patch
    case "OPTIONS": self = .options
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HttpMethod/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .post
    case 2: self = .`get`
    case 3: self = .head
    case 4: self = .put
    case 5: self = .delete
    case 6: self = .patch
    case 7: self = .options
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("HTTP_METHOD_UNSPECIFIED")
    case .post: return try container.encode("POST")
    case .`get`: return try container.encode("GET")
    case .head: return try container.encode("HEAD")
    case .put: return try container.encode("PUT")
    case .delete: return try container.encode("DELETE")
    case .patch: return try container.encode("PATCH")
    case .options: return try container.encode("OPTIONS")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
